### ISSUE TITLE
[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\yolov3\insect\quarrying-insect-id-master\insectid\models/quarrying_insect_detector.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by Anne668** [quarrying/quarrying-insect-id#2]
Excuse me, how to modify this error after running demo.py
onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\yolov3\insect\quarrying-insect-id-master\insectid\models/quarrying_insect_detector.onnx failed:Protobuf parsing failed.

The full version error message is as follows：
C:\Users\ZNKZ\miniconda3\envs\insectid\pythonw.exe D:/yolov3/insect/quarrying-insect-id-master/demo.py
Traceback (most recent call last):
  File "D:/yolov3/insect/quarrying-insect-id-master/demo.py", line 51, in <module>
    detector = InsectDetector()
  File "D:\yolov3\insect\quarrying-insect-id-master\insectid\detector.py", line 40, in __init__
    super(InsectDetector, self).__init__(model_path)
  File "D:\yolov3\insect\quarrying-insect-id-master\insectid\base.py", line 13, in __init__
    self.sess = onnxruntime.InferenceSession(model_path, sess_options)
  File "C:\Users\ZNKZ\miniconda3\envs\insectid\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\ZNKZ\miniconda3\envs\insectid\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from D:\yolov3\insect\quarrying-insect-id-master\insectid\models/quarrying_insect_detector.onnx failed:Protobuf parsing failed.

**Comment by quarrying** [comment]
You can download *.onnx files in https://github.com/quarrying/quarrying-insect-id/tree/master/insectid/models directly.

Because I store *.onnx using GIT LFS, if your git doesn't support LFS, *.onnx may not be downloaded.

**Comment by zz-zik** [comment]
我也是这种问题，重新下载了还是不行

**Comment by haroon830** [comment]
I think every one is getting this error. can you please help us??
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\Haroon Munir\Music\quarrying-insect-id-master\insectid\models/quarrying_insect_identifier.onnx failed:Protobuf parsing failed.
